version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  bot:
    build: ./bot
    environment:
      TELEGRAM_BOT_TOKEN: "7277152508:AAGPJuTo-F1288IJYBFdLmxsmm5WB-y6XTk"
