version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: notmap
      POSTGRES_USER: notmap_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"

  bot:
    build:
      context: ./bot
    environment:
      TELEGRAM_BOT_TOKEN: "7277152508:AAGPJuTo-F1288IJYBFdLmxsmm5WB-y6XTk"
    depends_on:
      - db

  server:
    build:
      context: ./server
    environment:
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"
